spring.application.name=emaildataview


#configurations
spring.main.banner-mode=off

#MongoDB connections
spring.data.mongodb.uri=mongodb+srv://pereirawedson1996:wedsonpereira@cluster0.5vjwaiv.mongodb.net
spring.data.mongodb.database=emailreplies

logging.level.root=off
spring.security.user.name=wedson
spring.security.user.password=12345



