spring.application.name=emaildataview


#configurations
spring.main.banner-mode=off

#database connections
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/?user=hr
spring.datasource.username=${DATABASE_USERNAME:thumbeja.publicity@123}
spring.datasource.password=${DATABASE_PASSWORD:thumbeja.publicity@123}
